# fly.toml app configuration file generated for kople-cms on 2024-10-16T19:27:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kople-cms'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 8080
  path = ''
